### ISSUE TITLE
Failed to add Status resolver

### ISSUE THREAD

**Issue by jagamypriera** [HydroBlockchain/snowflake-dashboard#21]
Always fail to perform gas estimation when trying to add resolver.

**Snowflake Dashboard**
![screen shot 2019-01-28 at 01 25 20](https://user-images.githubusercontent.com/4131801/51805095-d62c1800-229b-11e9-8d50-9a307e48d085.png)

**Metamask**
![screen shot 2019-01-28 at 01 26 37](https://user-images.githubusercontent.com/4131801/51805111-0673b680-229c-11e9-87c2-12fb5cfe22e8.png)

![screen shot 2019-01-28 at 02 14 50](https://user-images.githubusercontent.com/4131801/51805636-91f04600-22a2-11e9-8780-f828fd4c0c99.png)

**Comment by jagamypriera** [comment]
it seems snowflake address for Status resolver is not right
on the blockchain, Status was initialised with snowflake address: `0x223d9d7a9960a9d39f57d3ae37fa7080856f3c35`
but, on the snowflake-dashboard it's set to `0x47aC2F343926868e892Ba53a9D09e98bf6124460`
when i check both of snowflake contract, it has different function of `addResolver` (etherscan, line `385`)

**Comment by jagamypriera** [comment]
i've made new contract for Status.
`0x22c2005376dfCE374F3c096f708735E30039Afa4`

**Comment by NoahHydro** [comment]
Thanks for this @jagamypriera ! Should be fixed now, I've updated the existing Status smart contract to point to the new snowflake contract. Good catch :)
